### ISSUE TITLE
I have added utf-8 char encoding

### ISSUE THREAD

**Issue by FlowDownTheRiver** [dynamiccreator/whisper-typer-tool#2]
I had a little bit of trouble from time to time and it was complaining about characters,so I added utf-8.I also added model loading sound so when it is loaded we know it is functional.You may want to add language support instead of auto detection if you want.So that we can force the model to translation etc. Anyway Just wanted to thank you for the tool.
[whisper-typer-tool.zip](https://github.com/dynamiccreator/whisper-typer-tool/files/10574345/whisper-typer-tool.zip)

**Comment by dynamiccreator** [comment]
Thanks.I'm glad to hear that you like the tool. I have taken over your solution, but changed the model again to "tiny", as this was best working on a standard device like a mac book pro with no powerful GPU.
